[package]
name = "rust-test-webapp"
version = "0.1.0"
authors = ["matthewreader"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["frontend", "backend", "common"]
default-members = ["backend"]